################################### English language #####################################
[en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1

[en.params]
home = "Home"
# copyright
copyright = "Copyright &copy; 2025 Markaz Matiyat (The Ride of Knowledge)"



################################### French language #####################################
[fr]
languageName = "Fr"
languageCode = "fr-fr"
contentDir = "content/french"
weight = 2

[fr.params]
home = "Accueil"
# copyright
copyright = "Copyright &copy; 2025 Markaz Matiyat (The Ride of Knowledge)"

